### ISSUE TITLE
No code autocomplete or hover suggestions 

### ISSUE THREAD

**Issue by inexxt** [haskelly-dev/Haskelly#79]
Hi,
I'm having some problems with code autocomplete and hover suggestions.

 - `Ubuntu 16.04 LTS`
 - `intero 0.1.31`
 - `Stack 1.6.5`
 - `VS Code 1.24.0`

As I hover over function, nothing but a small box appears (as in the picture below).

![screenshot from 2018-06-07 03-31-37](https://user-images.githubusercontent.com/9115750/41073469-bffa9526-6a03-11e8-9bc8-e8cf04780500.png)

Code autocompletion doesn't work at all.

I've already tried to reinstall intero/haskelly, with no effect.

**Comment by chipbuster** [comment]
I installed this extension about 20 minutes ago and found the exact same problem.

  - `Arch Linux`
  - `intero 0.1.31`
  - `stack 1.7.1`
  - `VSCode 1.23.1`

I cannot install `stack-run` right now due to some resolver issues, but I don't expect that this would be the issue (let me know if I'm wrong!)

I also don't see anything of note in the dev console, just `[Extension Host] Trying new Intero for document`

**Comment by dainslef** [comment]
I have same problem, both in Windows & Linux  & macOS.

**Comment by goekboet** [comment]
I ran into this a couple of times. For me it worked on some files and not on others, though. Adding the module to the exposed-modules entry in my .cabal file solved this i my case:
```
library
  exposed-modules:
      Module1,
      Module2 -- When module 2 wasn't added empty box on hover 
  other-modules:
      Paths_haskell_book
  hs-source-dirs:
      src
  build-depends:
      base >=4.7 && <5
  default-language: Haskell2010
```

**Comment by midnio** [comment]
I have same issue.

**Comment by martrik** [comment]
Hello! Sorry for the late reply, we're not really maintaining Haskelly very actively lately. Could you please provide any error message that you might see in the Developer Console (to open it go into the Commands Palette and type "Toggle Developer Tools").

**Comment by littlebenlittle** [comment]
```
INFO no standard startup: not a new window
console.ts:136 [Extension Host] Trying new Intero for document main.hs and workDir undefined
log.ts:171   ERR read ECONNRESET: Error: read ECONNRESET
	at exports._errnoException (util.js:1050:11)
	at Pipe.onread (net.js:581:26)
```
